version: "3.2"
services:
    auth-service:
        build: ./auth-service
        # 'rabbitmq-server' will be available as a network reference inside this service 
        # and this service will start only after the RabbitMQ service has.
        # depends_on:
        #    - rabbitmq-server
        # Keep it running.  
        tty: true
        # Map port 3000 on the host machine to port 3000 of the container.
        ports:
            - "3000:3000"
        volumes:
            - './auth-service:/auth-service'

# Host volumes used to store code.
volumes:
    auth-service:
